services:
  app:
    build: ./front/
    volumes:
      - ./front:/front
    ports:
      - 3006:3000
  api:
    build: ./back/
    volumes:
      - ./back:/back
    ports:
      - 8006:8000
    depends_on:
      - db
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=menu_app
  db:
    image: mysql:8.0
    platform: linux/arm64/v8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: menu_app
      MYSQL_CHARACTER_SET_SERVER: utf8mb4
      MYSQL_COLLATION_SERVER: utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --innodb-use-native-aio=0

volumes:
  mysql_data: