name: 🤯 バグ・不具合修正
description: バグなどの不具合を修正する際に使用します
title: "[BUG] "
labels: ["バグ・不具合修正"]
body:
  - type: textarea
    id: bug_summary
    attributes:
      label: 🔍 どんな問題が起きていますか？
      description: 詳細・修正箇所と命名規則・備考を入力してください
      placeholder: |
        ## 詳細

        ## 修正箇所と命名規則

        ## 備考
    validations:
      required: true